### ISSUE TITLE
Add to local deployment (kind) the standalone console UI

### ISSUE THREAD

**Issue by eranra** [netobserv/network-observability-operator#124]

**Comment by eranra** [comment]
@jpinsonneau ^^

**Comment by jpinsonneau** [comment]
@eranra what about having all the time the `standalone` page hosted in the console plugin pod ? :smile_cat: 
So you will be able to open the page from a specific route or use the plugin if available.

**Comment by eranra** [comment]
@jpinsonneau ^^^ this is an interesting thought ... what about authentication/security... is there a need for more work so this route will be secured somehow ???

**Comment by jotak** [comment]
Side note: in my README rewritting PR ( https://github.com/netobserv/network-observability-operator/pull/125/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R72 ) , I've left some space to mention the standalone console. I think it would be great to deploy it, not only for local deployment on kind, but more generally when the openshift console is not available. It's aligned with what Julien suggested, I guess.
