### ISSUE TITLE
Release version 0.1.1 blocker

### ISSUE THREAD

**Issue by pweil-** [netobserv/network-observability-operator#87]
I see a release [0.1.1-rc](https://github.com/netobserv/network-observability-operator/releases/tag/v0.1.1) was cut and I wasn't invited to any release party.  This is clearly a blocker bug.  PTAL.

@davegord

**Comment by davegord** [comment]
@pweil-  you took all the budget with you when you left

**Comment by jotak** [comment]
@davegord @pweil- let's not repeat that mistake for GA

**Comment by pweil-** [comment]
SGTM...resolving, for now....
